#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# disabling strict host key checking

scp -o "StrictHostKeyChecking"=no -i "$4" "$1" "$3@$2:~/"

# checking transfer status

if [ $? -eq 0 ]
then
	echo "Transfered successfully"
else
	echo "Transfered Failed"
fi
